version: "3.5"
services:
  # server:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #     args:
  #       - http_proxy
  #       - https_proxy
  #       - no_proxy
  #   image: stephs-virtual-cookbook/server:latest
  #   ports:
  #     - "8081:8081"
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cookbook
